FROM quay.io/lyfe00011/test:beta

RUN git clone https://github.com/Mbo254/YuiChan /root/Yuichan
WORKDIR /root/Mbp254/
RUN yarn install --no-audit
*\\(Nobgms)
RUN cp -R /root/Utils/* /root/YuiChan
RUN npm install supervisor -g
CMD ["node", "bot.js"]
 
